ReportDefinitions:
- reportName: MCollectReceiptRegister
  summary: Report is used for audit and year-end finance reconciliation activities by the ULBs. It also serves as the data dump needed by the ULBs.
  version: 1.0.0
  moduleName: mcollect-reports
  sourceColumns:
  - name: receiptnumber
    label: reports.pt.receiptnumber
    type: string
    source: pt
    total: false
  - name: receiptdate
    label: reports.pt.receiptdate
    type: string
    source: pt
    total: false
  - name: businessservice
    label: reports.pt.businessservice
    type: string
    source: pt
    total: false
  - name: totaldue
    label: reports.pt.totaldue
    type: string
    source: pt
    total: false
  - name: amountcollected
    label: reports.pt.amountCollected
    type: string
    source: pt
    total: false
  - name: payername
    label: reports.pt.payername
    type: string
    source: pt
    total: false
  - name: transactionnumber
    label: reports.pt.transactionnumber
    type: string
    source: pt
    total: false
  - name: paymentmode
    label: reports.pt.paymentmode
    type: string
    source: pt
    total: false
  searchParams:
  - name: fromDate
    label: reports.pt.fromDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND ed.receiptdate >= $fromDate
  - name: toDate
    label: reports.pt.toDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND ed.receiptdate <= $toDate
  - name: receiptstatus
    label: receiptstatus
    type: singlevaluelist
    pattern: 'list://New:New,Deposited:Deposited,Dishonoured:Dishonoured'
    source: pt
    isMandatory: false
    searchClause: AND ep.paymentstatus <= $receiptstatus
query: |
       SELECT ed.receiptnumber,payerName,To_char(To_timestamp(ed.receiptdate / 1000), 'DD/MM/YYYY') AS paymentdate,
       transactionnumber,totaldue,totalamountpaid AS amountCollected,paymentmode,ed.businessservice,
       ep.paymentstatus AS receiptstatus FROM egcl_payment AS ep JOIN egcl_paymentdetail AS ed ON ep.id = ed.paymentid 
       where 1=1 AND ep.paymentstatus in ('NEW','DEPOSITED','DISHONOURED')
