ReportDefinitions:
- reportName: MCollectReceiptRegister
  summary: Report is used for audit and year-end finance reconciliation activities by the ULBs. It also serves as the data dump needed by the ULBs. 
  version: 1.0.0
  moduleName: mcollect-reports
  sourceColumns:
  - name: receiptnumber
    label: reports.pt.receiptnumber
    type: string
    source: pt
    total: false
  - name: paymentdate
    label: reports.pt.paymentdate
    type: string
    source: pt
    total: false
  - name: businessservice
    label: reports.pt.businessservice
    type: string
    source: pt
    total: false
  - name: totaldue
    label: reports.pt.totaldue
    type: string
    source: pt
    total: false
  - name: amountCollected
    label: reports.pt.amountCollected
    type: string
    source: pt
    total: false
  - name: payerName
    label: reports.pt.payerName
    type: string
    source: pt
    total: false
  - name: transactionnumber
    label: reports.pt.transactionnumber
    type: string
    source: pt
    total: false
  - name: paymentmode
    label: reports.pt.paymentmode
    type: string
    source: pt
    total: false
  - name: receiptstatus
    label: reports.pt.receiptstatus
    type: string
    source: pt
    total: false
  searchParams:
  - name: fromDate
    label: reports.pt.fromDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND ed.receiptdate >= $fromDate
  - name: toDate
    label: reports.pt.toDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND ed.receiptdate <= $toDate
  - name: receiptstatus
    label: receiptstatus
    type: singlevaluelist
    pattern: 'list://New:New,Deposited:Deposited,Dishonoured:Dishonoured'
    source: pt
    isMandatory: false
    searchClause: AND ep.paymentstatus <= $receiptstatus
  query: |
        SELECT receiptnumber,payerName,transactionnumber,totaldue,ed.businessservice,paymentmode,To_char(To_timestamp(ed.receiptdate / 1000), 'DD/MM/YYYY') AS paymentdate,
        totalamountpaid AS amountCollected,ep.paymentstatus AS receiptstatus FROM egcl_payment AS ep
        JOIN egcl_paymentdetail AS ed ON ep.id = ed.paymentid where 1=1 AND ep.paymentmode in ('DD','CHEQUE','ONLINE','CASH','CARD')
  orderby: order by ed.receiptdate desc;
