ReportDefinitions:
- reportName: MCollectReceiptRegister
  summary: Report is used for audit and year-end finance reconciliation activities by the ULBs. It also serves as the data dump needed by the ULBs. 
  version: 1.0.0
  moduleName: mcollect-reports
  sourceColumns:
  - name: receiptnumber
    label: reports.pt.receiptnumber
    type: string
    source: pt
    total: false
  - name: paymentdate
    label: reports.pt.paymentdate
    type: string
    source: pt
    total: false
  - name: businessservice
    label: reports.pt.businessservice
    type: string
    source: pt
    total: false
  - name: totaldue
    label: reports.pt.totaldue
    type: string
    source: pt
    total: false
  - name: amountCollected
    label: reports.pt.amountCollected
    type: string
    source: pt
    total: false
  - name: payerName
    label: reports.pt.payerName
    type: string
    source: pt
    total: false
  - name: transactionnumber
    label: reports.pt.transactionnumber
    type: string
    source: pt
    total: false
  - name: paymentmode
    label: reports.pt.paymentmode
    type: string
    source: pt
    total: false
  - name: receiptstatus
    label: reports.pt.receiptstatus
    type: string
    source: pt
    total: false
  searchParams:
  - name: fromDate
    label: reports.pt.fromDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND ed.receiptdate >= $fromDate
  - name: toDate
    label: reports.pt.toDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND ed.receiptdate <= $toDate
  - name: receiptstatus
    label: receiptstatus
    type: singlevaluelist
    pattern: 'list://New:New,Deposited:Deposited,Dishonoured:Dishonoured'
    source: pt
    isMandatory: false
    searchClause: AND ep.paymentstatus <= $receiptstatus
  query: |
        SELECT receiptnumber,payerName,transactionnumber,totaldue,ed.businessservice,paymentmode,To_char(To_timestamp(ed.receiptdate / 1000), 'DD/MM/YYYY') AS paymentdate,
        totalamountpaid AS amountCollected,ep.paymentstatus AS receiptstatus FROM egcl_payment AS ep
        JOIN egcl_paymentdetail AS ed ON ep.id = ed.paymentid where 1=1 AND ep.paymentmode in ('DD','CHEQUE','ONLINE','CASH','CARD')
  orderby: order by ed.receiptdate desc
  
- reportName: MCollectCollectionReport
  summary: It helps administrators track the collection in the ULB and the employee collection performance. 
  version: 1.0.0
  moduleName: mcollect-reports
  sourceColumns:
  - name: receiptnumber
    label: reports.pt.receiptnumber
    type: string
    source: pt
    total: false
  - name: locality
    label: reports.pt.locality
    type: string
    source: pt
    total: false
  - name: collectorname
    label: reports.pt.collectorname
    type: string
    source: pt
    total: false
  - name: paymentinstrument
    label: reports.pt.paymentinstrument
    type: string
    source: pt
    total: false
  - name: transactionnumber
    label: reports.pt.transactionnumber
    type: string
    source: pt
    total: false
  - name: amountCollected
    label: reports.pt.amountCollected
    type: string
    source: pt
    total: false
  - name: paymentdate
    label: reports.pt.paymentdate
    type: string
    source: pt
    total: false
  searchParams:
  - name: fromDate
    label: reports.pt.fromDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND ed.receiptdate >= $fromDate
  - name: toDate
    label: reports.pt.toDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND ed.receiptdate <= $toDate
  - name: paymentinstrument
    label: paymentinstrument
    type: singlevaluelist
    pattern: 'list://Cash:Cash,Online:Online,Card:Card,DD:DD,Cheque:Cheque'
    source: pt
    isMandatory: false
    searchClause: AND paymentmode = $paymentinstrument  
  query: |
        SELECT receiptnumber,payeraddress AS locality,payerName AS collectorname,To_char(To_timestamp(ed.receiptdate / 1000), 'DD/MM/YYYY') AS paymentdate,
        transactionnumber,totalamountpaid AS amountCollected,paymentmode AS paymentinstrument FROM egcl_payment AS ep
        JOIN egcl_paymentdetail AS ed ON ep.id = ed.paymentid where 1=1 AND ep.paymentmode in ('DD','CHEQUE','ONLINE','CASH','CARD')
  orderby: order by ed.receiptdate desc
  orderby: order by ed.receiptdate desc;

- reportName: ChallanRegister
  summary: Report is used to track and understand the challans generated, outstanding amount, & different status of the challans. 
  version: 1.0.0
  moduleName: challan-register-reports
  sourceColumns:
  - name: service
    label: reports.mcollect.service
    type: string
    source: challan-register-reports
    total: false
  - name: locality
    label: eports.mcollect.locality
    type: string
    source: challan-register-reports
    total: false
  - name: totalchallans
    label: reports.mcollect.totalchallans
    type: string
    source: challan-register-reports
    total: false
  - name: status
    label: reports.mcollect.status
    type: string
    source: challan-register-reports
    total: false
  - name: totalamount
    label: reports.mcollect.totalamount
    type: string
    source: challan-register-reports
    total: false
  searchParams:
  - name: service
    label: reports.mcollect.service
    type: multivaluelist
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=pb&moduleName=BillingService&masterName=BusinessService&filter=[?(@.type=='Adhoc')]|$.MdmsRes.BillingService.BusinessService.*.code|$.MdmsRes.BillingService.BusinessService.*.businessService
    source: common
    wrapper: true
    state: true
    isMandatory: false
    isLocalisationRequired: true
    localisationPrefix: BILLINGSERVICE_BUSINESSSERVICE_
    searchClause: AND REGEXP_REPLACE(service,'\..*','') IN ($service)
  - name: fromDate
    label: reports.mcollect.fromDate
    type: epoch
    source: challan-register-reports
    isMandatory: true
    searchClause: AND ec.taxPeriodFrom >= $fromDate
  - name: toDate
    label: reports.mcollect.toDate
    type: epoch
    source: challan-register-reports
    isMandatory: true
    searchClause: AND ec.taxPeriodTo <= $toDate
  - name: status
    label: reports.mcollect.status
    type: singlevaluelist
    pattern: http://egov-mdms-service:8080/egov-mdms-service/v1/_get?tenantId=pb&moduleName=mCollect&masterName=applicationStatus&filter=[?(@.active)]|$.MdmsRes.mCollect.applicationStatus.*.code|$.MdmsRes.mCollect.applicationStatus.*.code
    source: challan-register-reports
    isMandatory: false
    searchClause: AND status = $status
  - name: locality
    label: reports.mcollect.locality
    type: singlevaluelist
    pattern: http://egov-location.egov:8080/egov-location/location/v11/boundarys/_search?hierarchyTypeCode=ADMIN&boundaryType=Locality&tenantId=pb|$.TenantBoundary[0].boundary.*.code|$.TenantBoundary[0].boundary.*.name
    source: challan-register-reports
    wrapper: true
    isMandatory: false
    searchClause: AND locality = $locality
  query: |
        select ec.businessService as service , eca.locality as locality, ec.applicationStatus as status, count(*)as totalchallans, sum(bd.totalamount) as totalamount from eg_echallan as ec 
        join eg_challan_address as eca on ec.id = eca.echallanId
        join egbs_billdetail_v1 as bd on ec.challanNo = bd.consumercode where 1=1
  groupby: group by ec.businessService, eca.locality, ec.applicationStatus
