---
ReportDefinitions:
- reportName: WnsReceiptRegisterReport
  decryptionPathId: WnsReceiptRegisterReport
  summary: WnS Receipt Register Report
  version: 1.0.0
  moduleName: rainmaker-wns
  sourceColumns:
  - name: receiptnumber
    label: report.wns.receiptnumber
    type: string
    source: wns
    total: false
  - name: receiptdate
    label: report.wns.receiptdate
    type: string
    source: wns
    total: false
  - name: service
    label: report.wns.service
    type: string
    source: wns
    total: false
  - name: name
    label: report.wns.name
    type: string
    source: wns
    total: false
  - name: totalamountpaid
    label: report.wns.totalamountpaid
    type: number
    source: wns
    total: false
  - name: payername
    label: report.wns.payername
    type: string
    source: wns
    total: false
  - name: transactionnumber
    label: report.wns.transactionnumber
    type: string
    source: wns
    total: false
  - name: chequeno
    label: report.wns.chequeno
    type: string
    source: wns
    total: false
  searchParams:
  - name: fromDate
    label: FromDate
    type: epoch
    source: wns
    isMandatory: true
    searchClause: AND u.date >= $fromDate
  - name: toDate
    label: ToDate
    type: epoch
    source: wns
    isMandatory: true
    searchClause: AND u.date  <= $toDate 
  - name: receiptStatus
    label: reports.wns.receiptStatus
    type: string
    source: wns
    isMandatory: false
    searchClause: AND u.status = $receiptStatus
  - name: serviceName
    label: reports.wns.serviceName
    type: string
    source: wns
    isMandatory: false
    searchClause: AND u.service = $serviceName
  - name: collectionOperator
    label: CollectionOperator
    type: string
    source: wns
    isMandatory: false
    searchClause: AND u.createdby = $collectionOperator
  query: select * from ((select egcl_payment.createdby,eg_sw_connection.tenantid,receiptdate as date,receiptnumber, egcl_bill.status, to_char(To_timestamp(receiptdate / 1000), 'DD/MM/YYYY') as receiptdate, CASE WHEN egcl_bill.businessservice='SW' THEN 'Sewerage' ELSE NULL END as service,eg_user.name, totalamountpaid,payername, transactionnumber, CASE WHEN paymentmode='CHEQUE' THEN instrumentnumber ELSE null END as chequeno from egcl_payment inner join egcl_paymentdetail on egcl_payment.id=egcl_paymentdetail.paymentid inner join egcl_bill on egcl_paymentdetail.billid=egcl_bill.id inner join eg_sw_connection on egcl_bill.consumercode=connectionno inner join eg_sw_connectionholder on eg_sw_connection.id=eg_sw_connectionholder.connectionid inner join eg_user on eg_sw_connectionholder.userid=eg_user.uuid)  UNION ALL (select egcl_payment.createdby,eg_ws_connection.tenantid,receiptdate as date,receiptnumber, egcl_bill.status,to_char(To_timestamp(receiptdate / 1000), 'DD/MM/YYYY') as receiptdate, CASE WHEN egcl_bill.businessservice='WS' THEN 'Water' ELSE NULL END as service,eg_user.name, totalamountpaid, payername, transactionnumber , CASE WHEN paymentmode='CHEQUE' THEN instrumentnumber ELSE null END as chequeno from egcl_payment inner join egcl_paymentdetail on egcl_payment.id=egcl_paymentdetail.paymentid inner join egcl_bill on egcl_paymentdetail.billid=egcl_bill.id inner join eg_ws_connection on egcl_bill.consumercode=connectionno inner join eg_ws_connectionholder on eg_ws_connection.id=eg_ws_connectionholder.connectionid inner join eg_user on eg_ws_connectionholder.userid=eg_user.uuid)) as u where u.tenantid=$tenantid 