ReportDefinitions:
- reportName: PTReceiptRegister
  summary: Report is used for audit, day-end, and year-end finance reconciliation activities 
  version: 1.0.0
  moduleName: receipt-register-report
  sourceColumns:
  - name: receiptnumber
    label: reports.pt.receiptnumber
    type: string
    source: pt
    total: false
  - name: paymentdate
    label: reports.pt.paymentdate
    type: string
    source: pt
    total: false
  - name: amountCollected
    label: reports.pt.amountCollected
    type: string
    source: pt
    total: false
  - name: payerName
    label: reports.pt.payerName
    type: string
    source: pt
    total: false
  - name: transactionnumber
    label: reports.pt.transactionnumber
    type: string
    source: pt
    total: false
  - name: paymentmode
    label: reports.pt.paymentmode
    type: string
    source: pt
    total: false
  searchParams:
  - name: fromDate
    label: reports.pt.fromDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND ed.receiptdate >= $fromDate
  - name: toDate
    label: reports.pt.toDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND ed.receiptdate <= $toDate
  query: |
        SELECT receiptnumber,payerName,To_char(To_timestamp(ed.receiptdate / 1000), 'DD/MM/YYYY') AS paymentdate,
        transactionnumber,totalamountpaid AS amountCollected,paymentmode FROM egcl_payment AS ep
        JOIN egcl_paymentdetail AS ed ON ep.id = ed.paymentid where 1=1
  orderby: order by ed.receiptdate desc

- reportName: PTCollectionReport
  summary: It helps administrators track the collection in the ULB and the employee collection performance. 
  version: 1.0.0
  moduleName: receipt-register-report
  sourceColumns:
  - name: receiptnumber
    label: reports.pt.receiptnumber
    type: string
    source: pt
    total: false
  - name: locality
    label: reports.pt.locality
    type: string
    source: pt
    total: false
  - name: collectorname
    label: reports.pt.collectorname
    type: string
    source: pt
    total: false
  - name: paymentinstrument
    label: reports.pt.paymentinstrument
    type: string
    source: pt
    total: false
  - name: transactionnumber
    label: reports.pt.transactionnumber
    type: string
    source: pt
    total: false
  - name: amountCollected
    label: reports.pt.amountCollected
    type: string
    source: pt
    total: false
  - name: paymentdate
    label: reports.pt.paymentdate
    type: string
    source: pt
    total: false
  searchParams:
  - name: fromDate
    label: reports.pt.fromDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND rh.receiptdate >= $fromDate
  - name: toDate
    label: reports.pt.toDate
    type: epoch
    source: pt
    isMandatory: true
    searchClause: AND rh.receiptdate <= $toDate
  - name: instrumenttype
    label: instrumenttype
    type: singlevaluelist
    pattern: 'list://Cash:Cash,Online:Online,Card:Card,DD:DD,Cheque:Cheque'
    source: pt
    isMandatory: false
    searchClause: AND instrumenttype = $paymentinstrument  
  query: |
        SELECT rh.id,rh.location AS locality,rhh.collectiontype AS collectorname,ih.instrumenttype AS paymentinstrument,rh.transactionid AS transactionnumber,rhh.totalamount AS amountcollected,rhh.receiptnumber,To_char(To_timestamp(rh.receiptdate / 1000), 'DD/MM/YYYY') AS paymentdate 
        FROM egcl_receiptheader_v1 AS rh JOIN egcl_receiptheader_v1_history AS rhh ON (rh.id=rhh.id) 
        JOIN egcl_receiptinstrument_v1 AS ri ON rhh.id = ri.receiptheader JOIN egcl_instrumentheader_v1 AS ih ON ih.id = ri.instrumentheader where 1=1
  orderby: order by rh.receiptdate desc
